--- #ejemplo
- hosts: webservers
  become: yes
  tasks:
  - name: instalar apache2
    apt:
      update_cache: true 
      name: apache2 
      state: present
  - name: crear index
    file:
      name: /var/www/html/html/index.html
      state: touch
  - name: agregar contenido
    lineinfile:
      line: "El apache2 funciona"
      path: /var/www/html/html/index.html
  - name: iniciar apache2
    service:
      name: apache2
      state: started
